# Generated by Django 4.1.6 on 2023-02-09 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('calories_burned_per_hour', models.IntegerField()),
                ('is_global', models.BooleanField(blank=True, null=True)),
                ('approved_by_admin', models.BooleanField(blank=True, null=True)),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('is_global', models.BooleanField(blank=True, null=True)),
                ('approved_by_admin', models.BooleanField(blank=True, null=True)),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemLabel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie_counter_app.dailyrecord')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie_counter_app.fooditem')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='labels',
            field=models.ManyToManyField(to='calorie_counter_app.fooditemlabel'),
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie_counter_app.activity')),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie_counter_app.dailyrecord')),
            ],
        ),
    ]
