# Generated by Django 4.1.6 on 2023-02-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealsrecord',
            name='total_calorie_consumed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
