# Generated by Django 4.1.6 on 2023-02-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
