# Generated by Django 4.1.6 on 2023-02-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0002_mealsrecord_total_calorie_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='total_calorie_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
