# Generated by Django 4.1.6 on 2023-02-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0002_alter_dailyrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
