# Generated by Django 4.1.6 on 2023-02-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0003_activity_total_calorie_burned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='total_calorie_burned',
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='total_calorie_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
