# Generated by Django 4.1.6 on 2023-02-13 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter_app', '0004_remove_activity_total_calorie_burned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
