# Generated by Django 4.1.6 on 2023-02-13 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorie_counter_app', '0005_alter_fooditemlabel_name_mealsrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityrecord',
            name='daily_record',
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
